nome = "Ewerson Pulquerio Santos"

print("Só o primeiro")
print(nome[0])
print()
print("Só stop")
print(nome[:7])
print()
print("Só start")
print(nome[8:])
print()
print("Start e Stop")
print(nome[8:17])
print()
print("Start, Stop, Step")
print(nome[8:17:2])
print()
print("Completo")
print(nome[:])
print()
print("Invertido")
print(nome[::-1])
